sudo: required
services:
  - docker

before_install:
  - docker build -t giovanny .

script:
  - docker run giovanny

notifications:
  email:
    - fredy.ballesteros@correounivalle.edu.co
    - carlos.hidalgo@correounivalle.edu.co
    - leidy.carvajal.o@correounivalle.edu.co
