sudo: required
services:
  - docker

before_install:
  - docker build -t giovanny .

notifications:
  email:
    recipients:
      - jose.madrid@correounivalle.edu.co
      - carlos.hidalgo@correounivalle.edu.co
    on_success: always # default: change
    on_failure: always # default: always
